/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'GenerateFile': EventHandler<{ scheduleId: string; customerId: string; customerEmail: string; fileType: string; format: string }, never>
    'ScheduleChecker': CronHandler<{ topic: 'file.generate'; data: { scheduleId: string; customerId: string; customerEmail: string; fileType: string; format: string } }>
    'CreateSchedule': ApiRouteHandler<{ customerId: string; customerEmail: string; scheduleType: 'daily' | 'weekly' | 'monthly-first-weekday' | 'monthly-last-weekday' | 'custom'; timezone?: string; fileType?: string; format?: 'excel' | 'csv' | 'pdf'; config: { dayOfWeek?: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday'; time?: string; cronExpression?: string; weekOfMonth?: 'first' | 'last' } }, ApiResponse<201, { success: boolean; message: string; data: { scheduleId: string; nextRun: string; schedule?: unknown } }>, never>
  }
}